name: React CI

on: 
  push:
    branches:
     -"main"
jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x, 18.x ]

      steps:
       - uses: actions/checkout@v1
       - run: npm install
       - run: npm run start
       - run: npm test
       - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'public'      # optional: defaults to entire repository